<a href="https://colab.research.google.com/github/JulioDeca/Workshop26.1---16.03.2026-20.03.2026/blob/main/Desafio18.03.2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
for c in range (1,11):
  print(c)
Usuario = int(input"Digite um Numero Inteiro")

1
2
3
4
5
6
7
8
9
10

In [24]:
Numero = int(input("Digite um numero inteiro"))
for i in range (1,11):
  resultado= Numero*i
  print(Numero,"x",i,"=",resultado)

Digite um numero inteiro10
10 x 1 = 10
10 x 2 = 20
10 x 3 = 30
10 x 4 = 40
10 x 5 = 50
10 x 6 = 60
10 x 7 = 70
10 x 8 = 80
10 x 9 = 90
10 x 10 = 100

In [30]:
Usuario = int(input("Digite um numero inteiro"))

while Usuario < 0:
  print("Numero Invalido")
  Usuario = int(input("Digite um numero inteiro"))
for i in range (1,11):
  while Usuario !=0:
  resultado = Usuario * i
  print ()

IndentationError: expected an indented block after 'while' statement on line 7 (1349921360.py, line 8)

In [32]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

df = pd.read_csv('dados_nao_tratados.csv')

df.head()

Saving dados_nao_tratados.csv to dados_nao_tratados.csv

   id    nome         idade data_inscricao nota ativo
0   1     Ana            25     2023-05-12  8.5   Sim
1   2   Bruno  vinte e três     2023/13/01  9.0  TRUE
2   3   Carla            30            NaN  NaN   Não
3   4  Daniel           NaN     2022-07-15  7.2   sim
4   5   Érica            27     2022-08-XX    8     e

In [35]:
import pandas as pd

df = pd.read_csv('dados_nao_tratados.csv')
df

   id       nome         idade data_inscricao nota  ativo
0   1        Ana            25     2023-05-12  8.5    Sim
1   2      Bruno  vinte e três     2023/13/01  9.0   TRUE
2   3      Carla            30            NaN  NaN    Não
3   4     Daniel           NaN     2022-07-15  7.2    sim
4   5      Érica            27     2022-08-XX    8      e
5   6  Francisco            29     15/09/2022  dez  FALSE
6   7   Gabriela            21     2023-01-05   10   TRUE
7   8   Henrique            19     2023-02-30  9.5    nao
8   9      Ivana            11     2023-03-10  NaN    Yes
9  10       José             ?     2022-11-25  6.7    sim

In [10]:
# @title Default title text
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

plt.style.use('ggplot')

def gerar_temperaturas():

  return np.random.randint(20,25 ,7)

dias = ["Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado", "Domingo"]

temperaturas = gerar_temperaturas()

def criar_dataframe(dias, temperaturas):

  df = pd.DataFrame({
      "dias": dias,
      "temperaturas (C°) ": temperaturas
  })

  return df

  df = criar_dataframe(dias, temperaturas)

print ("\n Tabela de Temperatuas:\n")
print(df)

media = df["Temperatura (°C)"].mean()
maxima = df["Temperatura (°C)"].max()
minima = df["Temperatura (°C)"].min()

print("\n Análise")
print(f"Média da semana: {media: .2f} °C")
print(f"Temperatura máxima: {maxima} °C")
print(f"Temperatura mínima: {minima} °C")

df.to_csv("Temperaturas_semana.csv", index=False)
print("\n Arquivo 'temperaturas_semana' salvo!")

plot()
plt.xlabel("Dia")
plt.ylabel("Temperatura (°C)")
plt.grid()
plt.show()

plt.figure()
plt.bar(df["Dia"], df["Temperatura (°C)"])
plt.title("📊 Temperatura por Dia")
plt.xlabel("Dia")
plt.ylabel("Temperatura (°C)")
plt.show()

 Tabela de Temperatuas:

NameError: name 'df' is not defined